# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="A universal pastebin tool, written in Haskell."
HOMEPAGE="http://hackage.haskell.org/package/haste"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.4
		dev-haskell/curl
		dev-haskell/mtl
		>=dev-lang/ghc-6.8.2"
