# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal eutils

MY_PN="GPipe"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A functional graphics API for programmable GPUs"
HOMEPAGE="http://www.haskell.org/haskellwiki/GPipe"
SRC_URI="http://hackage.haskell.org/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="~dev-haskell/boolean-0.0.1[profile?]
		>=dev-haskell/glut-2.1.2.1[profile?]
		>=dev-haskell/list-tries-0.4.1[profile?]
		<dev-haskell/list-tries-0.5[profile?]
		>=dev-haskell/opengl-2.2.3.0[profile?]
		dev-haskell/transformers[profile?]
		~dev-haskell/vec-0.9.9[profile?]
		~dev-haskell/vec-boolean-1.0.4[profile?]
		>=dev-lang/ghc-7.0.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"

S="${WORKDIR}/${MY_P}"

src_prepare() {
	epatch "${FILESDIR}/vec-0.9.9.diff"
}
