# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.17

EAPI=4

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="GPipe"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A functional graphics API for programmable GPUs"
HOMEPAGE="http://www.haskell.org/haskellwiki/GPipe"
SRC_URI="http://hackage.haskell.org/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="~dev-haskell/boolean-0.0.1[profile?]
		~dev-haskell/glut-2.2.2.0[profile?]
		=dev-haskell/list-tries-0.4*[profile?]
		dev-haskell/mtl[profile?]
		~dev-haskell/opengl-2.4.0.1[profile?]
		~dev-haskell/vec-0.9.7[profile?]
		~dev-haskell/vec-boolean-1.0.3[profile?]
		>=dev-lang/ghc-6.12.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2.3"

S="${WORKDIR}/${MY_P}"
