# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.19

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Lambdabot is a development tool and advanced IRC bot"
HOMEPAGE="http://haskell.org/haskellwiki/Lambdabot"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		dev-haskell/arrows
		>dev-haskell/binary-0.2
		dev-lang/brainfuck
		>=dev-haskell/cabal-1.6
		dev-haskell/data-memocombinators
		dev-haskell/haskell-src
		>=dev-haskell/haskell-src-exts-0.4.8
		dev-haskell/http
		dev-haskell/iospec
		dev-haskell/lambdabot-utils
		>=dev-haskell/logict-0.4.2
		dev-haskell/monadrandom
		>dev-haskell/mtl-2
		dev-haskell/network
		dev-haskell/numbers
		>=dev-haskell/oeis-0.2
		dev-haskell/parsec
		dev-haskell/random
		dev-haskell/readline
		dev-haskell/regex-compat
		>=dev-haskell/show-0.3
		dev-haskell/syb
		dev-haskell/tagsoup
		dev-haskell/unlambda
		dev-haskell/utf8-string
		dev-haskell/vector-space
		>=dev-lang/ghc-6.10.4"
