# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.2

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-r3

DESCRIPTION="Pure, mergeable, succinct Int sets"
HOMEPAGE="https://github.com/pxqr/intset"
EGIT_REPO_URI="https://github.com/haasn/intset.git"
EGIT_COMMIT="v${PV}"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	|| ( ( >=dev-haskell/bits-extras-0.1.2:=[profile?]
		   >=dev-lang/ghc-7.4.1:= )
		 >=dev-lang/ghc-7.10.3:= )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( dev-haskell/quickcheck
			dev-haskell/test-framework
			>=dev-haskell/test-framework-quickcheck2-0.3 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag test testing)
}
