# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin"
inherit haskell-cabal git-2 bash-completion-r1

DESCRIPTION="Generate a bash completion from the GHC manpage"
HOMEPAGE="http://hackage.haskell.org/package/ghc-man-completion"
EGIT_REPO_URI="git://github.com/headprogrammingczar/ghc-man-completion.git"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8
		>dev-haskell/parsec-3
		>=dev-lang/ghc-6.12.3
		dev-lang/perl
		sys-apps/man-db"

src_compile() {
	cabal_src_compile

	./dist/build/ghc-man-completion/ghc-man-completion -f ghc-man-completion
}

src_install() {
	dobashcomp "${S}/ghc-man-completion"
}
