# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Functional user interfaces"
HOMEPAGE="http://haskell.org/haskellwiki/Phooey"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="<dev-haskell/mtl-2[profile?]
		<dev-haskell/reactive-0.6[profile?]
		>=dev-haskell/typecompose-0.2[profile?]
		dev-haskell/wx[profile?]
		dev-haskell/wxcore[profile?]
		>=dev-lang/ghc-6.8.2"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-0"
