# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Monads with suspension and arbitrary-spot reentry"
HOMEPAGE="http://hackage.haskell.org/package/continue"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bifunctors-3.0:=[profile?]
		<dev-haskell/bifunctors-4:=[profile?]
		>=dev-haskell/monad-control-0.3:=[profile?]
		<dev-haskell/monad-control-1:=[profile?]
		>=dev-haskell/mtl-2.0:=[profile?]
		<dev-haskell/mtl-3:=[profile?]
		>=dev-haskell/semigroupoids-3.0:=[profile?]
		<dev-haskell/semigroupoids-4:=[profile?]
		>=dev-haskell/transformers-0.3:=[profile?]
		<dev-haskell/transformers-1:=[profile?]
		>=dev-haskell/transformers-base-0.4:=[profile?]
		<dev-haskell/transformers-base-1:=[profile?]
		>=dev-lang/ghc-7.4.1:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.10"
