# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

MY_PN="Xapian-Haskell"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Haskell bindings for the Xapian search engine"
HOMEPAGE="https://github.com/ocharles/Xapian-Haskell"
EGIT_REPO_URI="https://github.com/ocharles/Xapian-Haskell.git"

LICENSE="" # unknown upstream license
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/enumerator:=[profile?]
	>=dev-haskell/mtl-2.0:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	dev-libs/xapian
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

src_prepare() {
	epatch "${FILESDIR}"/${PN}.patch

	default_src_prepare
}
