# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-2

DESCRIPTION="A parallel wrapper for 'ghc --make'."
HOMEPAGE="https://github.com/23Skidoo/ghc-parmake"
EGIT_REPO_URI="git://github.com/23Skidoo/ghc-parmake.git"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-7.0.1"
DEPEND="${RDEPEND}
		=dev-haskell/temporary-1*[profile?]
		=dev-haskell/array-0.3*[profile?]
		test? ( >=dev-haskell/hunit-1.2.2.0
			>=dev-haskell/quickcheck-2.4.1.1
			>=dev-haskell/test-framework-0.4.1
			<dev-haskell/test-framework-0.5
			>=dev-haskell/test-framework-hunit-0.2.6
			<dev-haskell/test-framework-hunit-0.3
			>=dev-haskell/test-framework-quickcheck2-0.2.10
			<dev-haskell/test-framework-quickcheck2-0.3
		)
		>=dev-haskell/cabal-1.8"
