# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Fast generic automaton arrow transformer for AFRP"
HOMEPAGE="http://hackage.haskell.org/package/netwire"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/arrows-0.4.4[profile?]
		>=dev-haskell/deepseq-1.1.0[profile?]
		>=dev-haskell/lifted-base-0.1.0[profile?]
		>=dev-haskell/monad-control-0.3.0[profile?]
		>=dev-haskell/mtl-2.0.1[profile?]
		>=dev-haskell/random-1.0.0[profile?]
		>=dev-haskell/stm-2.2.0[profile?]
		>=dev-haskell/time-1.2.0[profile?]
		>=dev-haskell/vector-0.9[profile?]
		>=dev-haskell/vector-space-0.7.8[profile?]
		>=dev-lang/ghc-7.0.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
