# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.19

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal darcs

DESCRIPTION="Flexible wire arrows for FRP"
HOMEPAGE="http://hackage.haskell.org/package/netwire"
EDARCS_REPOSITORY="http://hub.darcs.net/ertes/netwire/"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/arrows-0.4[profile?]
		<dev-haskell/arrows-1[profile?]
		>=dev-haskell/bifunctors-0.1[profile?]
		<dev-haskell/bifunctors-4[profile?]
		>=dev-haskell/lifted-base-0.1[profile?]
		<dev-haskell/lifted-base-1[profile?]
		>=dev-haskell/monad-control-0.3[profile?]
		<dev-haskell/monad-control-1[profile?]
		>=dev-haskell/mtl-2.0[profile?]
		<dev-haskell/mtl-3[profile?]
		dev-haskell/netwire[profile?]
		>=dev-haskell/profunctors-0.1[profile?]
		<dev-haskell/profunctors-4[profile?]
		>=dev-haskell/random-1.0[profile?]
		<dev-haskell/random-2[profile?]
		>=dev-haskell/semigroups-0.8[profile?]
		<dev-haskell/semigroups-1[profile?]
		>=dev-haskell/tagged-0.4[profile?]
		<dev-haskell/tagged-1[profile?]
		>=dev-haskell/vector-0.9[profile?]
		<dev-haskell/vector-1[profile?]
		>=dev-haskell/vector-space-0.8[profile?]
		<dev-haskell/vector-space-1[profile?]
		>=dev-lang/ghc-7.6.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.10"
