# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Push-pull functional reactive programming"
HOMEPAGE="http://haskell.org/haskellwiki/reactive"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE=""	#Fixme: "OtherLicense", please fill in manually
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/category-extras-0.53.5[profile?]
		>=dev-haskell/checkers-0.2.3[profile?]
		>=dev-haskell/quickcheck-2.1.0.2[profile?]
		dev-haskell/random[profile?]
		>=dev-haskell/stream-0.3.1[profile?]
		>=dev-haskell/typecompose-0.8.0[profile?]
		>=dev-haskell/unamb-0.1.5[profile?]
		>=dev-haskell/vector-space-0.5[profile?]
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2"
