# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-2

DESCRIPTION="Networked stream transducers"
HOMEPAGE="http://github.com/ekmett/machines/"
EGIT_REPO_URI="git://github.com/ekmett/machines.git"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/comonad-3*:=[profile?]
		>=dev-haskell/free-3.1.1:=[profile?]
		<dev-haskell/free-4:=[profile?]
		>=dev-haskell/mtl-2:=[profile?]
		<dev-haskell/mtl-2.2:=[profile?]
		=dev-haskell/pointed-3*:=[profile?]
		=dev-haskell/profunctors-3*:=[profile?]
		=dev-haskell/semigroupoids-3*:=[profile?]
		>=dev-haskell/semigroups-0.8.3:=[profile?]
		<dev-haskell/semigroups-1:=[profile?]
		=dev-haskell/transformers-0.3*:=[profile?]
		>=dev-lang/ghc-6.12.1:="
DEPEND="${RDEPEND}
		test? ( >=dev-haskell/doctest-0.8
			<=dev-haskell/doctest-0.10
		)
		>=dev-haskell/cabal-1.10"
