# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A pure-Haskell SSH server library."
HOMEPAGE="http://darcsden.com/alex/ssh"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/asn1-data-0.6.1.2[profile?]
		<dev-haskell/asn1-data-0.7[profile?]
		dev-haskell/base64-string[profile?]
		dev-haskell/binary[profile?]
		dev-haskell/cereal[profile?]
		dev-haskell/crypto-api[profile?]
		=dev-haskell/crypto-pubkey-types-0.1*[profile?]
		dev-haskell/cryptohash[profile?]
		>=dev-haskell/hsopenssl-0.8[profile?]
		dev-haskell/network[profile?]
		dev-haskell/random[profile?]
		=dev-haskell/rsa-1.2*[profile?]
		dev-haskell/sha[profile?]
		dev-haskell/simpleaes[profile?]
		dev-haskell/split[profile?]
		dev-haskell/transformers[profile?]
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
