# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="BerkeleyDB"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Berkeley DB binding"
HOMEPAGE="http://www.haskell.org/haskellwiki/BerkeleyDBXML"
SRC_URI="http://hackage.haskell.org/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-6.10.1
		sys-libs/db"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.4"

S="${WORKDIR}/${MY_P}"
