# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A modern parser combinator library with convenient diagnostics"
HOMEPAGE="http://github.com/ekmett/trifecta/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/bifunctors-3.0*[profile?]
		>=dev-haskell/blaze-builder-0.3.0.1[profile?]
		<dev-haskell/blaze-builder-0.4[profile?]
		>=dev-haskell/blaze-html-0.4.1.6[profile?]
		<dev-haskell/blaze-html-0.5[profile?]
		>=dev-haskell/charset-0.3.2.1[profile?]
		<dev-haskell/charset-0.4[profile?]
		=dev-haskell/comonad-3.0*[profile?]
		>=dev-haskell/deepseq-1.2.0.1[profile?]
		<dev-haskell/deepseq-1.4[profile?]
		>=dev-haskell/fingertree-0.0.1[profile?]
		<dev-haskell/fingertree-0.1[profile?]
		>=dev-haskell/hashable-1.1.2.1[profile?]
		<dev-haskell/hashable-1.2[profile?]
		=dev-haskell/keys-3.0*[profile?]
		>=dev-haskell/mtl-2.0.1[profile?]
		<dev-haskell/mtl-2.2[profile?]
		=dev-haskell/pointed-3.0*[profile?]
		=dev-haskell/profunctors-3.0*[profile?]
		=dev-haskell/reducers-3.0*[profile?]
		=dev-haskell/semigroupoids-3.0*[profile?]
		>=dev-haskell/semigroups-0.8.3.1[profile?]
		<dev-haskell/semigroups-0.9[profile?]
		>=dev-haskell/terminfo-0.3.2[profile?]
		<dev-haskell/terminfo-0.4[profile?]
		>=dev-haskell/transformers-0.2[profile?]
		<dev-haskell/transformers-0.4[profile?]
		>=dev-haskell/unordered-containers-0.2.1[profile?]
		<dev-haskell/unordered-containers-0.3[profile?]
		>=dev-haskell/utf8-string-0.3.6[profile?]
		<dev-haskell/utf8-string-0.4[profile?]
		=dev-haskell/wl-pprint-extras-3.0*[profile?]
		=dev-haskell/wl-pprint-terminfo-3.0*[profile?]
		>=dev-lang/ghc-7.0.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
