# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Examples for the reactive-banana library, using wxHaskell."
HOMEPAGE="http://haskell.org/haskellwiki/Reactive-banana"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cabal-macosx-0.1[profile?]
		<dev-haskell/cabal-macosx-0.3[profile?]
		>=dev-haskell/reactive-banana-0.6.0.0[profile?]
		<dev-haskell/reactive-banana-0.7[profile?]
		>=dev-lang/ghc-6.12.1
		|| ( >=dev-haskell/wx-0.13.2.1[profile?] <dev-haskell/wx-0.90[profile?] >=dev-haskell/wx-0.90.0.1[profile?] <dev-haskell/wx-0.91[profile?] )
		|| ( >=dev-haskell/wxcore-0.13.2.1[profile?] <dev-haskell/wxcore-0.90[profile?] >=dev-haskell/wxcore-0.90.0.1[profile?] <dev-haskell/wxcore-0.91[profile?] )"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
