# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="In-memory storage with multiple keys using lenses and traversals"
HOMEPAGE="http://github.com/ekmett/tables/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/binary-0.5*:=[profile?]
		=dev-haskell/cereal-0.3*:=[profile?]
		=dev-haskell/comonad-3*:=[profile?]
		>=dev-haskell/hashable-1.1:=[profile?]
		<dev-haskell/hashable-1.3:=[profile?]
		>=dev-haskell/lens-3.8:=[profile?]
		<dev-haskell/lens-4:=[profile?]
		>=dev-haskell/profunctors-3.2:=[profile?]
		<dev-haskell/profunctors-4:=[profile?]
		>=dev-haskell/safecopy-0.6.3:=[profile?]
		<dev-haskell/safecopy-0.9:=[profile?]
		>=dev-haskell/transformers-0.2:=[profile?]
		<dev-haskell/transformers-0.4:=[profile?]
		>=dev-haskell/transformers-compat-0.1:=[profile?]
		<dev-haskell/transformers-compat-1:=[profile?]
		=dev-haskell/unordered-containers-0.2*:=[profile?]
		>=dev-lang/ghc-7.0.1:="
DEPEND="${RDEPEND}
		test? ( >=dev-haskell/doctest-0.9.1
		)
		>=dev-haskell/cabal-1.8"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-transformers2 \
		--flag=test-properties
}
