# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="GuiTV"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="GUIs for Tangible Values"
HOMEPAGE="http://haskell.org/haskellwiki/GuiTV"
SRC_URI="http://hackage.haskell.org/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/deeparrow[profile?]
		>=dev-haskell/phooey-2.0[profile?]
		>=dev-haskell/tv-0.4[profile?]
		>=dev-haskell/typecompose-0.2[profile?]
		>=dev-lang/ghc-6.8.2"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-0"

S="${WORKDIR}/${MY_P}"
