# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Shell interface to the FreeTheorems library."
HOMEPAGE="http://hackage.haskell.org/package/ftshell"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="public-domain"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-0
		>=dev-haskell/free-theorems-0.3.1.3
		<dev-haskell/free-theorems-0.4
		>=dev-haskell/mtl-1.0
		>=dev-haskell/shellac-0.9
		>=dev-haskell/shellac-readline-0.9
		>=dev-lang/ghc-6.8.2"
