# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.6

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A stream DSL for writing embedded C programs."
HOMEPAGE="http://leepike.github.com/Copilot/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/copilot-c99-0.2:=[profile?]
	dev-haskell/copilot-cbmc:=[profile?]
	>=dev-haskell/copilot-core-0.2.3:=[profile?]
	>=dev-haskell/copilot-language-0.4:=[profile?]
	>=dev-haskell/copilot-libraries-0.4:=[profile?]
	>=dev-haskell/copilot-sbv-0.6:=[profile?]
	dev-haskell/random:=[profile?]
	>=dev-lang/ghc-7.0.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10.0.0
"
