# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-2

DESCRIPTION="Wide-char bindings to the ncurses library"
HOMEPAGE="https://github.com/vimus/vimus"
EGIT_REPO_URI="git://github.com/vimus/vimus.git"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-6.10.4:=
	sys-libs/ncurses
"
DEPEND="${RDEPEND}
	dev-haskell/c2hs
	dev-haskell/utf8-string:=[profile?]
	>=dev-haskell/cabal-1.6.0.3
"

src_prepare() {
	rm -rf vimus.cabal src Setup.lhs
	mv ncursesw/* .
}
