# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Automatic generation of free theorems."
HOMEPAGE="http://hackage.haskell.org/package/free-theorems"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="public-domain"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/haskell-src-1.0[profile?]
		>=dev-haskell/haskell-src-exts-0.3.9[profile?]
		<dev-haskell/haskell-src-exts-0.4[profile?]
		>=dev-haskell/mtl-1.0[profile?]
		>=dev-haskell/syb-0.1.0.0[profile?]
		>=dev-lang/ghc-6.8.2"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2.3"
