# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="A fractal viewer."
HOMEPAGE="https://github.com/skypers/phraskell"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8
		=dev-haskell/mtl-2.1*
		=dev-haskell/sdl-0.6*
		=dev-haskell/transformers-0.3*
		>=dev-lang/ghc-7.6.1"
