# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="An interface to bitcoind."
HOMEPAGE="http://github.com/mndrix/network-bitcoin"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/aeson-0.6*:=[profile?]
		=dev-haskell/attoparsec-0.10*:=[profile?]
		>=dev-haskell/http-4000:=[profile?]
		>=dev-haskell/network-2.3:=[profile?]
		>=dev-haskell/text-0.11:=[profile?]
		>=dev-haskell/unordered-containers-0.2:=[profile?]
		>=dev-haskell/vector-0.10:=[profile?]
		>=dev-lang/ghc-7.6.1:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
