# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="hscurses swimming fish example"
HOMEPAGE="http://ui3.info/darcs/hscurses-fish-ex/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2
		dev-haskell/hscurses
		dev-haskell/random
		dev-haskell/safe
		>=dev-lang/ghc-6.8.2"
